import { Asset } from '../types/assets';

export const ASSET_CATALOG: Asset[] = [
  // Cars
  {
    id: 'car-sedan',
    type: 'Car',
    name: 'Used Sedan',
    cost: 10000,
    resaleValue: 7000,
    happinessBoost: 5,
    requiredAge: 18,
  },
  {
    id: 'car-suv',
    type: 'Car',
    name: 'New SUV',
    cost: 30000,
    resaleValue: 25000,
    happinessBoost: 10,
    requiredAge: 18,
  },
  {
    id: 'car-sports',
    type: 'Car',
    name: 'Sports Car',
    cost: 80000,
    resaleValue: 60000,
    happinessBoost: 20,
    requiredAge: 21,
  },
  // Houses
  {
    id: 'house-apartment',
    type: 'House',
    name: 'Small Apartment',
    cost: 150000,
    resaleValue: 120000,
    maintenanceCost: 5000,
    happinessBoost: 15,
    requiredAge: 21,
  },
  {
    id: 'house-suburban',
    type: 'House',
    name: 'Suburban Home',
    cost: 300000,
    resaleValue: 250000,
    maintenanceCost: 10000,
    happinessBoost: 25,
    requiredAge: 25,
  },
  {
    id: 'house-mansion',
    type: 'House',
    name: 'Luxury Mansion',
    cost: 1000000,
    resaleValue: 800000,
    maintenanceCost: 25000,
    happinessBoost: 50,
    requiredAge: 30,
  },
  // Businesses
  {
    id: 'business-food-truck',
    type: 'Business',
    name: 'Food Truck',
    cost: 50000,
    resaleValue: 40000,
    incomePerYear: 20000,
    requiredAge: 21,
  },
  {
    id: 'business-small-store',
    type: 'Business',
    name: 'Small Retail Store',
    cost: 200000,
    resaleValue: 150000,
    incomePerYear: 50000,
    requiredAge: 25,
  },
  {
    id: 'business-tech-startup',
    type: 'Business',
    name: 'Tech Startup',
    cost: 500000,
    resaleValue: 400000,
    incomePerYear: 150000,
    requiredAge: 28,
  },
];