import { Job } from '../types/career';

export const CAREER_PATHS = {
  BUSINESS: 'Business',
  TECH: 'Technology',
  MEDICAL: 'Medical',
  EDUCATION: 'Education',
  CREATIVE: 'Creative',
  SERVICE: 'Service',
} as const;

export const JOBS: Job[] = [
  // Entry level jobs
  {
    id: 'junior-developer',
    title: 'Junior Developer',
    level: 1,
    baseSalary: 40000,
    requiredEducation: 3,
    requiredSmarts: 70,
    requiredAge: 18,
    careerPath: CAREER_PATHS.TECH,
    description: 'Entry-level software development position.',
  },
  {
    id: 'sales-associate',
    title: 'Sales Associate',
    level: 1,
    baseSalary: 30000,
    requiredEducation: 2,
    requiredAge: 16,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Retail sales position.',
  },
  {
    id: 'administrative-assistant',
    title: 'Administrative Assistant',
    level: 1,
    baseSalary: 35000,
    requiredEducation: 2,
    requiredAge: 18,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Office administrative support position.',
  },
  {
    id: 'customer-service-rep',
    title: 'Customer Service Representative',
    level: 1,
    baseSalary: 32000,
    requiredEducation: 2,
    requiredAge: 18,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Customer support and service position.',
  },
  {
    id: 'junior-accountant',
    title: 'Junior Accountant',
    level: 1,
    baseSalary: 40000,
    requiredEducation: 2,
    requiredSmarts: 75,
    requiredAge: 18,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Entry-level accounting position.',
  },
  {
    id: 'marketing-coordinator',
    title: 'Marketing Coordinator',
    level: 1,
    baseSalary: 38000,
    requiredEducation: 2,
    requiredAge: 18,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Entry-level marketing position.',
  },
  {
    id: 'business-analyst',
    title: 'Business Analyst',
    level: 1,
    baseSalary: 45000,
    requiredEducation: 3,
    requiredSmarts: 80,
    requiredAge: 20,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Business analysis and strategy position.',
  },
  {
    id: 'nurse',
    title: 'Nurse',
    level: 1,
    baseSalary: 50000,
    requiredEducation: 4,
    requiredSmarts: 75,
    requiredAge: 20,
    careerPath: CAREER_PATHS.MEDICAL,
    description: 'Healthcare nursing position.',
  },
  {
    id: 'teacher',
    title: 'Teacher',
    level: 1,
    baseSalary: 35000,
    requiredEducation: 4,
    requiredSmarts: 70,
    requiredAge: 22,
    careerPath: CAREER_PATHS.EDUCATION,
    description: 'Elementary school teacher.',
  },
  {
    id: 'graphic-designer',
    title: 'Graphic Designer',
    level: 1,
    baseSalary: 45000,
    requiredEducation: 3,
    requiredAge: 18,
    careerPath: CAREER_PATHS.CREATIVE,
    description: 'Creative design position.',
  },
  {
    id: 'waiter',
    title: 'Waiter',
    level: 1,
    baseSalary: 25000,
    requiredAge: 16,
    careerPath: CAREER_PATHS.SERVICE,
    description: 'Restaurant service position.',
  },

  // Mid level jobs
  {
    id: 'senior-developer',
    title: 'Senior Developer',
    level: 2,
    baseSalary: 80000,
    requiredEducation: 5,
    requiredSmarts: 85,
    requiredAge: 25,
    careerPath: CAREER_PATHS.TECH,
    description: 'Experienced software development position.',
  },
  {
    id: 'manager',
    title: 'Manager',
    level: 2,
    baseSalary: 60000,
    requiredEducation: 4,
    requiredSmarts: 80,
    requiredAge: 25,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Business management position.',
  },
  {
    id: 'accountant',
    title: 'Accountant',
    level: 2,
    baseSalary: 65000,
    requiredEducation: 4,
    requiredSmarts: 85,
    requiredAge: 25,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Professional accounting position.',
  },
  {
    id: 'marketing-manager',
    title: 'Marketing Manager',
    level: 2,
    baseSalary: 70000,
    requiredEducation: 4,
    requiredSmarts: 80,
    requiredAge: 26,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Marketing department management.',
  },
  {
    id: 'sales-manager',
    title: 'Sales Manager',
    level: 2,
    baseSalary: 68000,
    requiredEducation: 4,
    requiredSmarts: 75,
    requiredAge: 25,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Sales team management position.',
  },
  {
    id: 'operations-manager',
    title: 'Operations Manager',
    level: 2,
    baseSalary: 72000,
    requiredEducation: 4,
    requiredSmarts: 80,
    requiredAge: 27,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Business operations management.',
  },
  {
    id: 'financial-analyst',
    title: 'Financial Analyst',
    level: 2,
    baseSalary: 75000,
    requiredEducation: 4,
    requiredSmarts: 85,
    requiredAge: 25,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Financial analysis and planning.',
  },
  {
    id: 'hr-manager',
    title: 'HR Manager',
    level: 2,
    baseSalary: 68000,
    requiredEducation: 4,
    requiredSmarts: 75,
    requiredAge: 26,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Human resources management.',
  },
  {
    id: 'doctor',
    title: 'Doctor',
    level: 2,
    baseSalary: 120000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 28,
    careerPath: CAREER_PATHS.MEDICAL,
    description: 'Medical doctor position.',
  },
  {
    id: 'professor',
    title: 'Professor',
    level: 2,
    baseSalary: 70000,
    requiredEducation: 6,
    requiredSmarts: 85,
    requiredAge: 30,
    careerPath: CAREER_PATHS.EDUCATION,
    description: 'University professor position.',
  },
  {
    id: 'art-director',
    title: 'Art Director',
    level: 2,
    baseSalary: 75000,
    requiredEducation: 5,
    requiredAge: 25,
    careerPath: CAREER_PATHS.CREATIVE,
    description: 'Senior creative position.',
  },
  {
    id: 'restaurant-manager',
    title: 'Restaurant Manager',
    level: 2,
    baseSalary: 50000,
    requiredEducation: 3,
    requiredSmarts: 75,
    requiredAge: 22,
    careerPath: CAREER_PATHS.SERVICE,
    description: 'Restaurant management position.',
  },

  // Senior level jobs
  {
    id: 'tech-lead',
    title: 'Tech Lead',
    level: 3,
    baseSalary: 150000,
    requiredEducation: 6,
    requiredSmarts: 95,
    requiredAge: 35,
    careerPath: CAREER_PATHS.TECH,
    description: 'Technical leadership position.',
  },
  {
    id: 'ceo',
    title: 'CEO',
    level: 3,
    baseSalary: 200000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 40,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Chief Executive Officer.',
  },
  {
    id: 'cfo',
    title: 'Chief Financial Officer',
    level: 3,
    baseSalary: 180000,
    requiredEducation: 6,
    requiredSmarts: 95,
    requiredAge: 38,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Chief Financial Officer - oversees financial operations.',
  },
  {
    id: 'coo',
    title: 'Chief Operating Officer',
    level: 3,
    baseSalary: 175000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 38,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Chief Operating Officer - manages operations.',
  },
  {
    id: 'cmo',
    title: 'Chief Marketing Officer',
    level: 3,
    baseSalary: 170000,
    requiredEducation: 6,
    requiredSmarts: 85,
    requiredAge: 37,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Chief Marketing Officer - leads marketing strategy.',
  },
  {
    id: 'vp-sales',
    title: 'Vice President of Sales',
    level: 3,
    baseSalary: 160000,
    requiredEducation: 5,
    requiredSmarts: 85,
    requiredAge: 35,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Executive sales leadership position.',
  },
  {
    id: 'vp-finance',
    title: 'Vice President of Finance',
    level: 3,
    baseSalary: 165000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 36,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Executive finance leadership position.',
  },
  {
    id: 'director-strategy',
    title: 'Director of Strategy',
    level: 3,
    baseSalary: 150000,
    requiredEducation: 6,
    requiredSmarts: 88,
    requiredAge: 35,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Strategic planning and business development.',
  },
  {
    id: 'managing-director',
    title: 'Managing Director',
    level: 3,
    baseSalary: 190000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 40,
    careerPath: CAREER_PATHS.BUSINESS,
    description: 'Senior executive management position.',
  },
  {
    id: 'surgeon',
    title: 'Surgeon',
    level: 3,
    baseSalary: 250000,
    requiredEducation: 6,
    requiredSmarts: 95,
    requiredAge: 35,
    careerPath: CAREER_PATHS.MEDICAL,
    description: 'Surgical specialist.',
  },
  {
    id: 'university-dean',
    title: 'University Dean',
    level: 3,
    baseSalary: 120000,
    requiredEducation: 6,
    requiredSmarts: 90,
    requiredAge: 45,
    careerPath: CAREER_PATHS.EDUCATION,
    description: 'Academic administration position.',
  },
  {
    id: 'creative-director',
    title: 'Creative Director',
    level: 3,
    baseSalary: 130000,
    requiredEducation: 5,
    requiredAge: 35,
    careerPath: CAREER_PATHS.CREATIVE,
    description: 'Executive creative position.',
  },
  {
    id: 'hotel-manager',
    title: 'Hotel Manager',
    level: 3,
    baseSalary: 80000,
    requiredEducation: 4,
    requiredSmarts: 80,
    requiredAge: 30,
    careerPath: CAREER_PATHS.SERVICE,
    description: 'Hospitality management position.',
  },
];

export const getJobsByPath = (path: string): Job[] => {
  return JOBS.filter(job => job.careerPath === path);
};

export const getJobsByLevel = (level: number): Job[] => {
  return JOBS.filter(job => job.level === level);
};

export const getJobById = (id: string): Job | undefined => {
  return JOBS.find(job => job.id === id);
};